apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-service
  name: weather-service
  namespace: world
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: weather-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-service
    spec:
      containers:
      - image: raspberrypi:32000/k8s-sbc-weather-service:develop-be90ceb-latest
        imagePullPolicy: Always
        name: weather-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8080
        command:
          - dotnet
          - /app/Kubernetes.Sbc.Weather.Service.dll
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: world-ui
  name: world-ui
  namespace: world
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: world-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: world-ui
    spec:
      containers:
      - image: raspberrypi:32000/k8s-sbc-ui-web:develop-be90ceb-latest
        imagePullPolicy: Always
        name: world-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command:
          - dotnet
          - /app/Kubernetes.Sbc.Ui.Web.dll
        env:
          - name: APP_VERSION
            value: "1.0.1"
          - name: WEATHER_SERVICE
            value: "http://weather-service:8080"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}