apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: world-ui
  name: world-ui
  namespace: world
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31320
  selector:
    app: world-ui
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-service
  name: weather-service
  namespace: world
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weather-service
status:
  loadBalancer: {}
