apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: world-ui
  name: world-ui
  namespace: world
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31320
  selector:
    app: world-ui
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: asia-weather
  name: asia-weather
  namespace: world
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: asia-weather
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: europe-weather
  name: europe-weather
  namespace: world
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: europe-weather
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: southamerica-weather
  name: southamerica-weather
  namespace: world
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: southamerica-weather
status:
  loadBalancer: {}